tailwind.config = {
  "darkMode": "class",
  "theme": {
    "extend": {
      "colors": {
        "secondary-fixed-dim": "#d0bcff",
        "on-primary-fixed": "#001f26",
        "tertiary-fixed-dim": "#ffb0cd",
        "on-primary-fixed-variant": "#004e5c",
        "surface-dim": "#0f131d",
        "on-secondary-fixed": "#23005c",
        "error": "#ffb4ab",
        "on-surface": "#dfe2f1",
        "tertiary-fixed": "#ffd9e4",
        "inverse-primary": "#00687a",
        "on-tertiary-container": "#780047",
        "on-tertiary-fixed": "#3e0022",
        "surface-variant": "#313540",
        "surface-container-highest": "#313540",
        "outline-variant": "#3d494c",
        "inverse-on-surface": "#2c303b",
        "primary": "#4cd7f6",
        "primary-fixed-dim": "#4cd7f6",
        "on-secondary": "#3c0091",
        "on-error": "#690005",
        "surface-bright": "#353944",
        "surface-container-high": "#262a35",
        "on-secondary-container": "#c4abff",
        "on-secondary-fixed-variant": "#5516be",
        "surface-container-lowest": "#0a0e18",
        "surface-container": "#1c1f2a",
        "on-tertiary": "#640039",
        "tertiary-container": "#ff79b4",
        "error-container": "#93000a",
        "surface-tint": "#4cd7f6",
        "inverse-surface": "#dfe2f1",
        "primary-fixed": "#acedff",
        "on-background": "#dfe2f1",
        "on-primary-container": "#00424f",
        "on-surface-variant": "#bcc9cd",
        "secondary": "#d0bcff",
        "tertiary": "#ffb0cd",
        "on-error-container": "#ffdad6",
        "background": "#0f131d",
        "on-primary": "#003640",
        "secondary-container": "#571bc1",
        "outline": "#869397",
        "on-tertiary-fixed-variant": "#8c0053",
        "secondary-fixed": "#e9ddff",
        "surface-container-low": "#171b26",
        "primary-container": "#06b6d4",
        "surface": "#0f131d"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "margin": "3rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.5rem",
        "margin-mobile": "1.25rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "gutter": "1.5rem"
      },
      "fontFamily": {
        "body-sm": ["Inter"],
        "headline-lg": ["Space Grotesk"],
        "display-mobile": ["Space Grotesk"],
        "label-code": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "label-caps": ["JetBrains Mono"],
        "display": ["Space Grotesk"],
        "headline-sm": ["Space Grotesk"]
      },
      "fontSize": {
        "body-sm": ["13px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "display-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-code": ["13px", { "lineHeight": "18px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "body-md": ["15px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.12em", "fontWeight": "600" }],
        "display": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "600" }]
      }
    }
  }
};
